main:
  domain           : 'mudasobwa.ru'

template:
  article          : 'index.tmpl'
  regex            : '^(\d{4}(\-\d{1,2}){0,5}\+?)+$'

settings :
  debug            : 0
  memos            : 5000
  rss              : 10
  rssformat        : 'RSS'

data :
  dir              : 'data'
  metadir          : 'meta'
  sorter           : 'Mudasobwa\Eblo\Cache::sorter'

tags :
  nicknames        : '\A[\p{L}\p{N}\d]+\s+[«“](.*)[»”]\s+[\p{L}\p{N}\d]+\Z'
  short_t          : '\A(.*)\Z'
  fablesse_oblige  : '(?i)Лабашев|Немиров|Дыбин|колхоз|археологическ|Берлин|Ираклео|Барселон'
